import "./globals.css";
import { Header } from "../components/header/Header";

import { mainMenu } from "./../__content/main-menu";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="dark:bg-zinc-900 dark:text-zinc-100">
        <Header id={mainMenu.id} menuItems={mainMenu.items} />
        <div id="page-layout" className="container mx-auto px-3 py-4">
          <main role="main">{children}</main>
        </div>
        <Analytics />
      </body>
    </html>
  );
}
