name: ci
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: next-image-extras test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Install
        run: npm install

      - name: Build next-image-extras
        run: npm run build --workspace=packages/next-image-extras

      - name: Run tests
        run: npm run test
