name: ci
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  cypress-run:
    name: cypress tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Install
        run: npm install

      - name: Build examples app
        run: npm run nextjs-example:build

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     install: false
      #     build: npm run nextjs-example:build
      #     start: npm run nextjs-example:start

  jest-test:
    name: next-image-extras jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Install
        run: npm install

      - name: Build next-image-extras
        run: npm run build --workspace=packages/next-image-extras

      - name: Run tests
        run: npm run test
