name: ci
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  cypress-run:
    name: cypress tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install
        run: npm install

      - name: Build next-image-plus package
        run: npm run build --workspace=packages/next-image-plus

      - name: Build www app
        run: npm run www:build

      - name: Start wwww app in the background
        run: npm run www:start &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          working-directory: apps/www

  jest-test:
    name: next-image-plus jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install
        run: npm install

      - name: Build next-image-plus
        run: npm run build --workspace=packages/next-image-plus

      - name: Run tests
        run: npm run test
